function   [obj]=getImageStackFiles(ImageStackObj)
% GUI for loading and mixing up to 3 image stacks
    scrnsize=get(groot,'ScreenSize');
    figsize=[scrnsize(3)-40,scrnsize(4)-90];
    figheight=figsize(2);
    figwidth=figsize(1);
    obj.fhandle=figure('Name','Channel mixer','MenuBar','none',...
        'Position',[30,60,figwidth,figheight],'Resize','off'); 
    obj.ImageStackObj=ImageStackObj;

    % set up axes and image
    obj.haxes=axes('Parent',obj.fhandle);
    set(obj.haxes,'Units','pixels');
    set(obj.haxes,'Position',[400,40,figwidth-410,figheight-60]);
    % create image object
    obj.image=image(zeros(1000,1000));
    set(obj.image,'Parent',obj.haxes);
    % set up channel 1 interface
    obj.ch1.pathstr=uicontrol(obj.fhandle,'Style','text',...
        'Position',[130,figheight-35,35,20],'String','Path: ',...
        'FontSize',10);
    obj.ch1.pathedit=uicontrol(obj.fhandle,'Style','edit',...
        'Position',[170,figheight-40,200,30],'String','',...
        'FontSize',10,'Tag','Ch1PathEdit','Enable','off');

    obj.ch1.colourlist=uicontrol(obj.fhandle,'Style','listbox',...
        'Position',[15,figheight-130,98,85],'String',...
        {'phase/DIC','green','red','blue','yellow'},...
        'FontSize',10,'Tag','Ch1ColourList','Callback',...
        {@ImageStack.ColourListCallback,obj},'TooltipString','Select colour before selecting files');
    
    obj.ch1.UniformIlluminationButton=uicontrol(obj.fhandle,'Style','pushbutton',...
            'Position',[115,figheight-120,53,53],'String',{'Bckgrnd'},...
        'FontSize',10,'Callback',@ImageStack.CorrectCh1Illum,'TooltipString','Select reference image before correcting uneven illumination and contrast',...
        'Enable','off');

    obj.ch1.filestxt=uicontrol(obj.fhandle,'Style','text',...
        'Position',[130,figheight-65,35,20],'String','Files: ',...
        'FontSize',10);

    obj.ch1.filesList=uicontrol(obj.fhandle,'Style','listbox',...
        'Position',[170,figsize(2)-130,200,85],'String','',...
        'FontSize',10,'Tag','Ch1FileList','Callback',@ImageStack.FileslistCallback,...
        'TooltipString','Select image to display','TooltipString','Have you selected the channel colour?');

    % set up Java dual range slider
    obj.ch1.DualThresholdSlider = com.jidesoft.swing.RangeSlider(0,100,0,100);  % min,max,low,high
    obj.ch1.DualThresholdSlider = javacomponent(obj.ch1.DualThresholdSlider, [90,figheight-165,280,30], obj.fhandle);
    set(obj.ch1.DualThresholdSlider, 'MajorTickSpacing',25, 'MinorTickSpacing',5, 'PaintTicks',true,  ...
         'Background',java.awt.Color.white, 'StateChangedCallback',@ImageStack.JSliderCallback);
    obj.ch1.DualThresholdText =uicontrol(obj.fhandle,'Style','text',...
        'Position',[16,figheight-165,70,30],'String','Thresholds',...
        'FontSize',10);

    obj.ch1.IntensitySlider = javax.swing.JSlider;

    obj.ch1.IntensitySlider=javacomponent(obj.ch1.IntensitySlider,[90,figheight-200,280,30], obj.fhandle);
    set(obj.ch1.IntensitySlider, 'MajorTickSpacing',25, 'MinorTickSpacing',5, 'PaintTicks',true,  ...
        'Background',java.awt.Color.white, 'StateChangedCallback',@ImageStack.JSliderCallback,...
        'Value',1);
    obj.ch1.IntensityText=uicontrol(obj.fhandle,'Style','text',...
        'Position',[16,figheight-200,70,30],'String','Intensity',...
        'FontSize',10);
    obj.ch1.loadPB=uicontrol(obj.fhandle,'Style','pushbutton',...
        'String','Tracking images','Position',[15,figheight-40,100,30],...
        'FontSize',10,'Callback',{@ImageStack.LoadCh1,obj},'Tag','LoadCh1PB','TooltipString','Have you selected the channel colour?');
    % calculate y offset
    y_offset=round(figheight/3.3);

    % channel 2

    obj.ch2.pathstr=uicontrol(obj.fhandle,'Style','text',...
        'Position',[130,figheight-35-y_offset,35,20],'String','Path: ',...
        'FontSize',10);
    obj.ch2.pathedit=uicontrol(obj.fhandle,'Style','edit',...
        'Position',[170,figheight-40-y_offset,200,30],'String','',...
        'FontSize',10,'Enable','off');

    obj.ch2.colourlist=uicontrol(obj.fhandle,'Style','listbox',...
        'Position',[15,figheight-130-y_offset,98,85],'String',...
        {'phase/DIC','green','red','blue','yellow'},...
        'FontSize',10,'Callback',{@ImageStack.ColourListCallback,obj},'TooltipString','Select the colour before loading files');
    
     obj.ch2.UniformIlluminationButton=uicontrol(obj.fhandle,'Style','pushbutton',...
        'Position',[115,figheight-120-y_offset,53,53],'String',{'Bckgrnd'},...
        'FontSize',10,'Callback',@ImageStack.CorrectCh2Illum,'TooltipString','Select reference image before correcting uneven illumination and contrast',...
        'Enable','off');

    obj.ch2.filestxt=uicontrol(obj.fhandle,'Style','text',...
        'Position',[130,figheight-65-y_offset,35,20],'String','Files: ',...
        'FontSize',10);

    obj.ch2.filesList=uicontrol(obj.fhandle,'Style','listbox',...
        'Position',[170,figsize(2)-130-y_offset,200,85],'String','',...
        'FontSize',10,'Enable','off','TooltipString','Select channel colour before selecting files');

   % set up Java dual range slider
    obj.ch2.DualThresholdSlider = com.jidesoft.swing.RangeSlider(0,100,0,100);  % min,max,low,high
    obj.ch2.DualThresholdSlider = javacomponent(obj.ch2.DualThresholdSlider, [90,figheight-165-y_offset,280,30], obj.fhandle);
    set(obj.ch2.DualThresholdSlider, 'MajorTickSpacing',25, 'MinorTickSpacing',5, 'PaintTicks',true,  ...
         'Background',java.awt.Color.white, 'StateChangedCallback',@ImageStack.JSliderCallback);
    obj.ch2.DualThresholdText =uicontrol(obj.fhandle,'Style','text',...
        'Position',[16,figheight-165-y_offset,70,30],'String','Thresholds',...
        'FontSize',10);

    obj.ch2.IntensitySlider = javax.swing.JSlider;
    obj.ch2.IntensitySlider=javacomponent(obj.ch2.IntensitySlider,[90,figheight-200-y_offset,280,30], obj.fhandle);
    set(obj.ch2.IntensitySlider, 'MajorTickSpacing',25, 'MinorTickSpacing',5, 'PaintTicks',true,  ...
        'Background',java.awt.Color.white, 'StateChangedCallback',@ImageStack.JSliderCallback,...
        'Value',1);
    obj.ch2.IntensityText=uicontrol(obj.fhandle,'Style','text',...
        'Position',[16,figheight-200-y_offset,70,30],'String','Intensity',...
        'FontSize',10);
    obj.ch2.loadPB=uicontrol(obj.fhandle,'Style','pushbutton',...
        'String','Ch2 images','Position',[15,figheight-40-y_offset,100,30],...
        'FontSize',10,'Callback',{@ImageStack.LoadCh2,obj},'Enable','off','TooltipString','Have you selected the colour of this channel?');
    % channel 3

    obj.ch3.pathstr=uicontrol(obj.fhandle,'Style','text',...
        'Position',[130,figheight-35-2*y_offset,35,20],'String','Path: ',...
        'FontSize',10);
    obj.ch3.pathedit=uicontrol(obj.fhandle,'Style','edit',...
        'Position',[170,figheight-40-2*y_offset,200,30],'String','',...
        'FontSize',10,'Enable','off');

    obj.ch3.colourlist=uicontrol(obj.fhandle,'Style','listbox',...
        'Position',[15,figheight-130-2*y_offset,98,85],'String',...
        {'phase/DIC','green','red','blue','yellow'},...
        'FontSize',10,'Callback',{@ImageStack.ColourListCallback,obj},'TooltipString','Select the channel colour before uploading files');
    
    obj.ch3.UniformIlluminationButton=uicontrol(obj.fhandle,'Style','pushbutton',...
        'Position',[115,figheight-120-2*y_offset,53,53],'String',{'Bckgrnd'},...
        'FontSize',10,'Callback',@ImageStack.CorrectCh3Illum,'TooltipString','Select reference image before correcting uneven illumination and contrast',...
        'Enable','off');

    obj.ch3.filestxt=uicontrol(obj.fhandle,'Style','text',...
        'Position',[130,figheight-65-2*y_offset,35,20],'String','Files: ',...
        'FontSize',10);

    obj.ch3.filesList=uicontrol(obj.fhandle,'Style','listbox',...
        'Position',[170,figsize(2)-130-2*y_offset,200,85],'String','',...
        'FontSize',10,'Enable','off','TooltipString','Select channel colour before loading files');

               % set up Java dual range slider
    obj.ch3.DualThresholdSlider = com.jidesoft.swing.RangeSlider(0,100,0,100);  % min,max,low,high
    obj.ch3.DualThresholdSlider = javacomponent(obj.ch3.DualThresholdSlider, [90,figheight-165-2*y_offset,280,30], obj.fhandle);
    set(obj.ch3.DualThresholdSlider, 'MajorTickSpacing',25, 'MinorTickSpacing',5, 'PaintTicks',true,  ...
         'Background',java.awt.Color.white, 'StateChangedCallback',@ImageStack.JSliderCallback);
    obj.ch3.DualThresholdText =uicontrol(obj.fhandle,'Style','text',...
        'Position',[16,figheight-165-2*y_offset,70,30],'String','Thresholds',...
        'FontSize',10);

    obj.ch3.IntensitySlider = javax.swing.JSlider;
    obj.ch3.IntensitySlider=javacomponent(obj.ch3.IntensitySlider,[90,figheight-200-2*y_offset,280,30], obj.fhandle);
    set(obj.ch3.IntensitySlider, 'MajorTickSpacing',25, 'MinorTickSpacing',5, 'PaintTicks',true,  ...
        'Background',java.awt.Color.white, 'StateChangedCallback',@ImageStack.JSliderCallback,...
        'Value',1);
    obj.ch3.IntensityText=uicontrol(obj.fhandle,'Style','text',...
        'Position',[16,figheight-200-2*y_offset,70,30],'String','Intensity',...
        'FontSize',10);

    obj.ch3.loadPB=uicontrol(obj.fhandle,'Style','pushbutton',...
        'String','Ch3 images','Position',[15,figheight-40-2*y_offset,100,30],...
        'FontSize',10,'Callback',{@ImageStack.LoadCh3,obj},'Enable','off','TooltipString','Have you selected the channel colour');
    % apply mixer to all images
    obj.ApplyToAllImagesPB=uicontrol(obj.fhandle,'Style','pushbutton',...
        'String','Apply to all images','Position',[15,15,180,30],...
        'FontSize',10,'Callback',@ImageStack.ApplyMixerToAllImages,'Enable','off',...
        'TooltipString','Apply mixer color maps to all images');
    obj.OKPB=uicontrol(obj.fhandle,'Style','pushbutton',...
        'String','OK','Position',[200,15,180,30],...
        'FontSize',10,'Callback',@ImageStack.Finish,'Enable','off',...
        'TooltipString','Save stack and colormaps');
    guidata(obj.fhandle,obj); % store all component handles with the figure 
    waitfor(obj.fhandle); % continue once figure is deleted

end
        
        